version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      microsoft:
        patterns:
          - Microsoft.*
      xunit:
        patterns:
          - xunit*
